### ISSUE TITLE
Gestión de memoria

### ISSUE THREAD

**Issue by JGonz0** [Damorgal/pai-2020-tarea-08#2]
No hay forma de saber si se pudo reservar correctamente el espacio en memoria, por ejemplo en:

https://github.com/Damorgal/pai-2020-tarea-08/blob/0bb33e01f3e535ac99314f51c3fa633a21e31a8d/DiegoM-JGonzaloP/heap.c#L53-L61

sugiero que cada vez que se utilice malloc() o calloc(), se verifique que todo esté en orden, 
e.g.

`if(h==NULL){printf("No ha sido posible asignar memoria"); exit(1);}`

Si esto ocurre, es conveniente terminar el programa.

**Comment by Damorgal** [comment]
Sí muy bien ahorita lo agrego
