### ISSUE TITLE
Rama "implementación-montículo"

### ISSUE THREAD

**Issue by JGonz0** [Damorgal/pai-2020-tarea-08#3]
Para evitar confusiones, estaré contribuyendo también en esta rama usando la versión más reciente de "heap.c".

Estaré trabajando en "specs.c" para realizar pruebas, y en "median.c" para la implementación de la aplicación.

**Comment by JGonz0** [comment]
Retiro lo dicho pues no va acorde al flujo de trabajo, sin embargo, si generaré una subrama dentro de esta para realizar las pruebas

**Comment by Damorgal** [comment]
Va me parece bien. Pero la de la applicación si creala en otra subrama de nuestra carpeta principal. Aunque creo que el flujo de trabajo solo deberían ser subramas de la carpeta principla.

**Comment by Damorgal** [comment]
Ah no! También retiro lo dicho jaja. Si no es subrama de esta no se van a poder ver los archivos. Aunque tal vez debemos de hacer esto cuando acabamos una sección:

hacer pull request en su propio repositorio cuando finalicen el código de una sección a la rama [integrante1-integrante2], por ejemplo reporte → integrante1-integrante.

**Comment by Damorgal** [comment]
ya le hice el pull request y merge, si quieres ya solo haz subramas de la carpeta principla.

**Comment by JGonz0** [comment]
De acuerdo, se crearon las subramas en la rama principal
