### ISSUE TITLE
Ciclo infinito

### ISSUE THREAD

**Issue by JGonz0** [Damorgal/pai-2020-tarea-08#4]
He estado testeando el código de "heap.c" y se presentan problemas al añadir un nuevo nodo que es menor a su padre:

https://github.com/Damorgal/pai-2020-tarea-08/blob/6bf1c75b9e7144b19963e08a4fefd11a55d6bc6f/DiegoM-JGonzaloP/heap.c#L104-L120

si no se realiza nunca el swap, el valor de k jamás cambiará, y el ciclo se repetirá indefinidamente.

Parece ser que todo está correcto con la función topDownHeapify y removeMax

**Comment by Damorgal** [comment]
Listo!
