### ISSUE TITLE
Extensión del montículo

### ISSUE THREAD

**Issue by JGonz0** [Damorgal/pai-2020-tarea-08#6]
Justo estaba trabajando con el problema de aplicación, y llegué a la conclusión que es más "cómodo" implementar las funciones de heap.c "en reverso", es decir, que en la cola de prioridad, la llave más pequeña sea la de mayor prioridad (valor más pequeño en la raíz).

Ya lo consulté con los ayudantes y no hay problema con ello, es exactamente la misma implementación de heap.c pero cambiando la orientación de los signos de comparación.

En la rama de implementación-aplicación, añadí el archivo "reverseheap.c" donde están estas definiciones.

Parece que la aplicación está completa, pero a ver que bugs se pueden encontrar :+1:

**Comment by Damorgal** [comment]
Sí, pues de hecho para la aplicación te pedían un montículo-min, así que lo teníamos que hacer jaja, otra forma era implementarlo genérico mandandole el apuntador a una función de comparación o con booleanos; solo que no leí antes la aplicación, una disculpa. Perfecto! ahorita lo reviso.
