### ISSUE TITLE
Detalle al remover elementos

### ISSUE THREAD

**Issue by JGonz0** [Damorgal/pai-2020-tarea-08#7]
Hice un pequeño test de "a ver que pasa" si se remueve de más en el heap:

https://github.com/Damorgal/pai-2020-tarea-08/blob/1a4a84619f2a3655ba839ea46e16ec366474241d/DiegoM-JGonzaloP/specs.c#L37-L53

Justo, me da un error en el assert, hmm supongo porque cuando se utiliza la función para remover:

https://github.com/Damorgal/pai-2020-tarea-08/blob/1a4a84619f2a3655ba839ea46e16ec366474241d/DiegoM-JGonzaloP/heap.c#L90-L98

el tamaño se reduce. 

Propongo que si el tamaño es de 0, no se reduzca su valor.

**Comment by Damorgal** [comment]
Listo, corregido.

**Comment by Damorgal** [comment]
También lo corregí en el reverseHeap
